Update buttons in the status bar and check for updates
mzmine/mzmine pull request #1035
Opened 2022-12-12 17:52 UTC by robinschmid

2022-12-13 08:43 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/MZmineGUI.java
> +      }
does this still have the correct color in dark mode?

2022-12-13 08:48 UTC, SteffenHeu requested changes

2022-12-13 08:48 UTC, SteffenHeu commented on src/main/java/io/github/mzmine/gui/MZmineGUI.java
> +      }
the hack to remove the link could be creating a new label every time, but i don't think that's feasible. Why not have a method `public void setStatusBarText(String message, Color textColor, URL url)` that will put a url, and the normal `public void setStatusBarText(String message, Color textColor)` removes said url by default

2022-12-15 00:16 UTC, robinschmid commented on src/main/java/io/github/mzmine/gui/MZmineGUI.java
> +      }
I removed this hardcoded color. We now just use the default color. and the negative color

2022-12-15 00:17 UTC, robinschmid commented
I have done exactly what you said. Good idea with one method. 
The colors are now the default style and the negative color if update needed. 
One method and the link is removed

2022-12-15 09:18 UTC, SteffenHeu approved these changes

2022-12-15 09:18 UTC, SteffenHeu commented
thanks

2022-12-15 09:18 UTC, merged