Add MS2Deepscore to MZMine
mzmine/mzmine pull request #1737
Opened 2024-03-22 12:43 UTC by niekdejonge

2024-04-03 19:45 UTC, robinschmid commented
I will look at it tomorrow. Sounds great so far.

2024-04-04 10:47 UTC, robinschmid commented on mzmine-community/build.gradle
> +    testImplementation(libs.djl.pytorch.engine)
You can remove these three lines and only keep the bundle above. 
That was me when you had the error with the library but that should be resolved.
After doing that just reload gradle project. There will be an icon after the change in the top right corner or you open the gradle tab and there is a reload gradle project button

2024-04-04 10:51 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public NDList tensorizeSpectrum(Scan Spectrum){
instead of Scan use its parent interface MassSpectrum - it has all the same methods. 
The data is always sorted by mz ascending. 
Most efficient way is to just do a simple for loop over the data points by index and spectrum.getNumberOfDataPoints()

2024-04-04 11:05 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public Double[][] predictMatrix(ArrayList<Scan> spectra1, ArrayList<Scan> spectra2){
List instead of ArrayList. You would always mention the parent types if your method does not depend on implementation details. ArrayList has just few special methods that you most likely dont use here.

2024-04-04 11:11 UTC, robinschmid commented on mzmine-community/src/test/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModelTest.java
> +            assertEquals(predictions.size(), 1);
switch values its expected, actual so
assertEquals(1, predictions.size());

2024-04-04 11:20 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +        return predictor.predict(new NDList(spectrumNDArray1, spectrumNDArray2, metadataNDArray1, metadataNDArray2));
interesting so thats how its defined in the model that you have spec1 spec2 meta1 meta2 in this order just in a single list and it wil combine the data internally?

2024-04-04 11:22 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public Double[][] predictMatrix(ArrayList<Scan> spectra1, ArrayList<Scan> spectra2){
We could use here List<SpectralTensor> a, ... b as input so that the precompute was already done somewhere else.

2024-04-04 11:22 UTC, robinschmid submitted a review, later dismissed
Great so far

2024-04-04 11:29 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public NDList tensorizeSpectrum(Scan Spectrum){
Creating a separate class for tensorization makes sense indeed. The reason I considered making it into a method here, is that the tensorization can be different per model and is therefore really a part of that particular model. Maybe an in-between solution: creating a separate class for tensorization, but creating a Tensorizer object in the constructor of MS2DeepscoreModel, based on the settings for that particular model.

2024-04-04 11:30 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public NDList tensorizeSpectrum(Scan Spectrum){
Alternatively we could also just hard code the settings for tensorization and just make it only compatible with the one version of MS2Deepscore model that we release. Which is in reality what I expect users to use anyway.

2024-04-04 11:32 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public NDList tensorizeSpectrum(Scan Spectrum){
Regarding Scan/MassSpectrum, thanks for the overview! This model needs precursor_mz and ionmode as well as input, so I think we will need to use Scan here.

2024-04-04 11:44 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +        return predictor.predict(new NDList(spectrumNDArray1, spectrumNDArray2, metadataNDArray1, metadataNDArray2));
Regarding the output: 
In python it is actually:
```python
def forward(self, spectra_tensors_1, spectra_tensors_2, metadata_1, metadata_2):
```
But in some examples it seemed that in java it expected this format, so that surprised me a bit as well, but it works like this.

2024-04-04 12:02 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +                          NDArray spectrumNDArray2,
The input actually are multiple spectra against multiple spectra. So NDArray is 2D the rows are the vectors representing one spectrum per row. So the output also is a list of predictions currently. 

Ideally in the end we could actually get an embedding out instead of the scores, since this implementation would be a lot faster for matrix comparisons, since the embedding calculation is the "expensive" step. This is also how we do it in the python version, but in a slightly different way, which was not (yet) easy to convert to java. 

I will try to get this to work, but it also might require some rewriting on the python end. 

In the end I want to have a pair_prediction and matrix_prediction method. These should indeed just return floats or list of floats.

2024-04-04 13:29 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public NDList tensorizeSpectrum(Scan Spectrum){
you could create an enum class with constants representing each model that we support (also looking into the future. You can either add a constructor and pass in the clear name and link to download the model or you just create methods in the enum like this:
```java
public enum MS2DeepScoreModels {
POSITIVE_V1, BOTH_POLARITIES_V1;

public String toString() {
  return switch(this) {
    case POSITIVE_V1 -> "Positive (v1)";
    case POSITIVE_V1 -> "Both polarities (v1)";
  };
}
```

2024-04-04 13:30 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public NDList tensorizeSpectrum(Scan Spectrum){
This enum could later be places in a combobox and can be used to decide which tensor to create

2024-04-04 13:34 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +                          NDArray spectrumNDArray2,
I think getting the embeddings would be great. And either we can then feed them to the model and get all pairs computed or just compute cosine in java. I got an easy parallel stream implementation to go thorugh all pairs

2024-04-04 13:36 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +        return predictor.predict(new NDList(spectrumNDArray1, spectrumNDArray2, metadataNDArray1, metadataNDArray2));
looks similar at least. 
So just giving a list of NDArrays in and the model will know how many to use etc

2024-04-08 07:28 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    public NDList tensorizeSpectrum(Scan Spectrum){
Yes, that might be an easy solution. We also generate a settings json in python, which also contains the information about tensor sizes. We could also use that to use the right settings. But at first we can just support only 1 model.

2024-04-08 07:28 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +        return predictor.predict(new NDList(spectrumNDArray1, spectrumNDArray2, metadataNDArray1, metadataNDArray2));
Yes, seems like it.

2024-04-24 13:14 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/ms2deepscore/MS2DeepscoreTask.java
> +  private final Double minScore;
this might be confusing at first and the auto create of variable will always make this a Double - just because it may be null at this point.
But we know that the score is never null - its not optional and need to be set. So you can make this a primitive double. This only has few implications but its always a nice way to also denote that it is not optional

2024-04-24 13:16 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/ms2deepscore/MS2DeepscoreTask.java
> +  }
Better remove this already its still here from copying the class

2024-04-24 13:17 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +   * Predicts the MS2Deepscore similarity
I guess this is old right. this just does the embedding not the similarity?

2024-04-24 13:27 UTC, robinschmid commented on mzmine-community/src/test/resources/models/ms2deepscore_model_settings.json
> +                "standard_deviation": 1000.0
Not sure where you defined this but shouldnt it be mean 500 standard deviation 500? or something similar?

2024-04-24 13:31 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SettingsMS2Deepscore.java
> +public record SettingsMS2Deepscore(@JsonProperty("embedding_dim") Integer embeddingDimension,
you can just add this above the class and that makes all names automatically use snake case in the json and camelCase in java.

@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)

Easiest way to adjust the names in this class is to hit rename (CTRL+ALT+R) on each variable and then max_mz would be maxMz in camelCase 
mzBinWidth...
Very optional - just something I thought to mention for future json works

2024-04-25 07:45 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/ms2deepscore/MS2DeepscoreTask.java
> +  }
Yes, I maybe should have clarified a bit more, but I did not work on any of the Module/Task/Parameter implementation since we worked on it since Friday, but have been working from the other end up, adding the core functionality of predicting MS2Deepscore embeddings and tensorizing spectra in separate classes (MS2DeepscoreModel, SpectrumTensorizer etc.) I still have to do the integration of both later.

2024-04-25 07:46 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +   * Predicts the MS2Deepscore similarity
Yes indeed, the similarity scoring I have now (after your reviewed) added to a parent class called EmbeddingBasedSimilarity

2024-04-25 07:56 UTC, niekdejonge commented on mzmine-community/src/test/resources/models/ms2deepscore_model_settings.json
> +                "standard_deviation": 1000.0
Yes, we could also have used these settings, but we didn't use it for training the model, so we cannot change it here. But it does not matter too much. It is just important for initialization of weights in a neural network that all input data is scaled somewhat similar, to have the training go efficiently. So this just has to ensure that the precursor mz has somewhat the same order of magnitute as the intensities we input. So 0.0 and 1000.0, but also 500 and 500 would do the trick.

2024-04-25 07:57 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SettingsMS2Deepscore.java
> +public record SettingsMS2Deepscore(@JsonProperty("embedding_dim") Integer embeddingDimension,
Ah thanks! Good to know

2024-05-09 08:34 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/EmbeddingBasedSimilarity.java
> +    double[][] result = new double[(int) shape[0]][(int) shape[1]];
Just to describe what is happening here. 
arrays (fixed size list or tuple in python) in Java have maximum size limited by integer thats why conversion to (int) is needed here

2024-05-09 13:11 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/EmbeddingBasedSimilarity.java
> +    NDArray norm2 = embedding2.square().sum(new int[]{1}).sqrt();
you can use embedding1.norm(new int[]{1}) instead.

2024-05-09 13:18 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/EmbeddingBasedSimilarity.java
> +    }
embedding1.transpose().div(norm1).transpose() does the same thing.

2024-05-09 13:34 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/EmbeddingBasedSimilarity.java
> +    return convertNDArrayToDoubleMatrix(embedding1.dot(embedding2.transpose()));
what I always wonder is - can we not do the whole matrix? Its super fast to calculate but one would only need to check A-B not B-A because the result is the same. 

Just a general thing

2024-05-09 13:51 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    NDManager manager = NDManager.newBaseManager();
maybe we can pass the manager into the constructor of the MS2DeepScoreModel - then from outside the caller can control the lifetime of the manager?

2024-05-09 13:54 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    Predictor<NDList, NDList> predictor = model.newPredictor();
This predictor piece also feels like it could be in the constructor so that its done once. Not sure how memory or CPU heavy it is... but could be better

2024-05-09 14:05 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SettingsMS2Deepscore.java
> +                                   @JsonProperty("intensity_scaling") float intensityScaling
just a more general comment. You can slab a naming convention on this and it will automatically translate from camelCase to snake_case.

Put this before the class - but then your names need to directly match, e.g., mzBinWidth --> mz_bin_width:
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)

Also you can default ignore or fail on unknown properties
@JsonIgnoreProperties(ignoreUnknown = true)

2024-05-09 14:09 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    this.numBins = (int) ((settings.maximumMZ() - settings.minimumMZ() / settings.binWidth()));
this will always round down - so maximum mz might not be captured by this. Just needs to be the same like in your python code but just to make sure. 
Otherwise. (int)Math.ceil( ... )

2024-05-09 14:14 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +        int binIndex = (int) ((mz - settings.minimumMZ() / settings.binWidth()));
braces are wrong?
should be (mz-minMZ) / binWidth

2024-05-09 14:16 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    }
sometimes the charge is not given. Maybe safer to default to positive mode or if the model could actually take the three options: postivie, negative, unknown like 1, -1, 0?

If the model cannot - then better to use POSITIVE as a plausible default

2024-05-09 14:21 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    @NotNull double precursorMZ = scan.getPrecursorMz();
Yeah. 
So you cannot put @NotNull on a double primitive because primitives cannot be null... 
Double objects (Double wraps a double) can be null and the return type of getPrecursorMz is Double so it could be null at this point.

I guess you never looked into GC-EI-MS data where you do not have precursor mz right? 
Is there an option to not provide the precursor mz? In case it is missing?
Usually we should have it for MS2 spectra.

2024-05-09 14:23 UTC, robinschmid commented on mzmine-community/src/test/resources/models/ms2deepscore_model_settings.json
> +                "standard_deviation": 1000.0
Ok I understand - this is not the mz 0 with SD 1000 but intensity...

2024-05-09 14:28 UTC, robinschmid commented on mzmine-community/src/test/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModelTest.java
> +          new double[][]{new double[]{1.0, 1.0, 0.0, 0.0}, new double[]{1.0, 0.0, 1.0, 1.0}});
just to make your life easier on this one. Here you can define the nested array just {}. Sometimes this is possible.
`new double[][]{{1.0, 1.0, 0.0, 0.0}, {1.0, 0.0, 1.0, 1.0}}`

2024-05-09 14:50 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/EmbeddingBasedSimilarity.java
> +    return convertNDArrayToDoubleMatrix(embedding1.dot(embedding2.transpose()));
maybe they already abstract this away in the native code.

2024-05-09 14:50 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/EmbeddingBasedSimilarity.java
> +    NDArray norm2 = embedding2.square().sum(new int[]{1}).sqrt();
combined with below you could rewrite it to:
```java
  public float[][] dotProduct2(NDArray embedding1, NDArray embedding2) {
    NDArray norm1 = embedding1.norm(new int[]{1});
    NDArray norm2 = embedding2.norm(new int[]{1});
    embedding1 = embedding1.transpose().div(norm1).transpose();
    embedding2 = embedding2.transpose().div(norm2).transpose();
    return convertNDArrayToDoubleMatrix(embedding1.dot(embedding2.transpose()));
  }
```

2024-05-09 14:54 UTC, robinschmid commented on mzmine-community/src/test/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModelTest.java
> +      similarityMatrix = model.predictMatrix(testSpectra, testSpectra);
Maybe we should also add a function for predictPairwise(testSpectra) with just one input where all spectra are compared pair wise. This is the case for molecular networking.
Then the embeddings only need to be created once.

2024-05-09 14:55 UTC, robinschmid requested changes
Great so far. I think we are close of getting this in. Just need to finalize the API to feed in either 2 lists of scans (library matching) or 1 list of scans that is compared pairwise (molecular networking).

2024-06-26 13:50 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    NDManager manager = NDManager.newBaseManager();
I did move it to the constructor. I added a method closeNdManager to MS2DeepscoreModel. So we can call this to ensure the ndManager is closed, when not needed anymore. Is that what you had in mind?

2024-06-26 13:53 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModel.java
> +    Predictor<NDList, NDList> predictor = model.newPredictor();
I have moved it to the constructor. I don't expect it to be super memory or CPU heave, but not fully sure. We can have a look at further optimization once we have everything up and running.

2024-06-26 14:32 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    this.numBins = (int) ((settings.maximumMZ() - settings.minimumMZ() / settings.binWidth()));
Good to check indeed! But it is the same as implemented in python.

2024-06-26 15:43 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +        int binIndex = (int) ((mz - settings.minimumMZ() / settings.binWidth()));
Good catch. The tests did not capture it because bin_width was 1.0...

2024-06-27 08:03 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    }
The model will use the ion mode as input, so a different prediction is made for a positive mode spectrum or a negative mode spectrum. So guessing is a bit dangerous, since it might give the wrong predictions. Is the ionmode something that can be easily set in MZMine, or if it is missing in the metadata it will remain missing? We could maybe add an option to set the ionmode in the MS2Deepscore module?

2024-06-27 08:04 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    @NotNull double precursorMZ = scan.getPrecursorMz();
This relates also to the above comment. We take the precursor mz and ionmode as input for this model. So the prediction is different if these values are different. MS2Deepscore is therefore only compatible with acquisition types that return an precursor mz. So for GC-EI-MS data it won't work.

2024-06-27 08:13 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    @NotNull double precursorMZ = scan.getPrecursorMz();
For now having precursor mz is null or polarity is null will throw a runtime error.

2024-06-27 08:22 UTC, niekdejonge commented on mzmine-community/src/test/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/MS2DeepscoreModelTest.java
> +          new double[][]{new double[]{1.0, 1.0, 0.0, 0.0}, new double[]{1.0, 0.0, 1.0, 1.0}});
Thanks! That makes everything a bit less verbose.

2024-06-27 08:25 UTC, niekdejonge commented
@robinschmid Thanks for the review! (and sorry it took so long before I had time again...) Really helpful, to have this quick feedback loop, to get myself familiar with the syntax. I have applied your changes, all your comments were clear. I will now have a look at integrating ms2deepscore with the MZMine modules. Once I have this working I will ask for a new review.

2024-06-27 13:28 UTC, ansgarkorf commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    @NotNull double precursorMZ = scan.getPrecursorMz();
So what would currently happen if some has DIA data? I am not sure if precursor info is added based on the MS1 scan. Maybe @SteffenHeu can answer this?

For now I suggest to mention the restrictions in a java doc and if we add MS2DeepScore as an option to a parameter set, it should always be disabled for MS1 data. I think all modules using similarity scores have a MS level or scan filter parameter, which could be checked.

2024-06-28 07:12 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    @NotNull double precursorMZ = scan.getPrecursorMz();
The precursor info is not added as scan info, but i guess you could take the row mz as a precursor in that case (for LC-DIA).

2024-06-28 07:18 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    @NotNull double precursorMZ = scan.getPrecursorMz();
We trained and tested MS2Deepscore only for LC MSMS data. I am not sure how similar DIA data becomes to DDA after processing. If that is very close we could consider using it for DIA as well, but otherwise I would just limit it to LC MSMS, since we have no clue how it will perform otherwise. 

We should of course ensure that this is handled well and does not result in any crashes.

2024-06-28 08:02 UTC, ansgarkorf commented on mzmine-community/src/main/java/io/github/mzmine/util/scans/similarity/impl/ms2deepscore/SpectrumTensorizer.java
> +    @NotNull double precursorMZ = scan.getPrecursorMz();
Yes, I agree. We also have to make sure to add these information in the documentation, e.g. optimized for DDA, untested for DIA.

2024-06-28 23:04 UTC, robinschmid commented
In our documentation you should find a part in intellij where you can add a file filter for the copyright header. So formats that it should not apply to.

2024-07-01 15:51 UTC, niekdejonge commented
@robinschmid The current version has all basic functionality. MS/MS spectral networking (ms2deepscore) works. We can select a model file. I have added a test file to the resources/models so you can use this for testing (but the results will be meaningless). The larger models I tested myself also work fine. And visualization in interactive ion identity molecular networking is working. 

Could you let me know if everything is implemented in a correct way and what steps we should still do?

2024-07-03 11:55 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/ms2deepscore/MS2DeepscoreParameters.java
> +          Objects.requireNonNull(FileAndPathUtil.resolveInMzmineDir("models")).toString()));
This should set the default to the users/.mzmine/models folder. However, I was not able to check this, since it seems to be overwritten by the last set directory. (which I did not no how to reset) So please double check if this is correct. @robinschmid

2024-07-03 12:16 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/ms2deepscore/MS2DeepscoreParameters.java
> +      FileSelectionType.OPEN, true);
It would be ideal if this field is updated automatically when we set the download folder. Or at least that the last folder is updated to reflect the location of the downloaded files. Is something like that easily doable?

2024-07-03 12:18 UTC, niekdejonge commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/ms2deepscore/MS2DeepscoreParameters.java
> +  public static final FileNameParameter ms2deepscoreSettingsFile = new FileNameParameter(
I gave the user now has a lot of options. Like where to store the downloaded models, or to use a different model etc. An alternative is to remove that option altogether and just always downloading the model to a predefined location. What do you think is most user friendly? @robinschmid

2024-07-11 13:48 UTC, SteffenHeu commented
Thank you for all the work @niekdejonge! Did @robinschmid and you discuss why MS2Deepscore does not implement the SpectralSimilarityFunction interface so we can use it everywhere where we use cosine similarity?

2024-07-11 14:39 UTC, robinschmid commented
we have to check it. And see if we can come up with a good strategy for this. Not sure if the interface design is good. 
Definitely need to check how we can combine it in one module in the end. Very different parameters needed for cosine / modified cosine than for MS2Deepscore.

2024-07-12 07:21 UTC, SteffenHeu commented
The input takes a parameter set, so i think that should not be a problem, or?

2024-07-15 04:38 UTC, robinschmid commented
MS2Deepscore works so differently that it does not really fit in. No mz tolerance, no minimum matched signals. 
```java
public abstract SpectralSimilarity getSimilarity(ParameterSet parameters, MZTolerance mzTol,
      int minMatch, DataPoint[] library, DataPoint[] query);
```

Best is to send a batch of spectral data to calculate the embeddings - then the similarity is a simple vector comparison by cosine sim. So the spectral alignment step is not needed. I think it might be good to have two interfaces somehow - one for vector based and one for spectral based.

2024-07-29 15:27 UTC, merged