Aird 2.0
mzmine/mzmine pull request #1806
Opened 2024-04-22 06:43 UTC by lumiaoshan

Fix bug for issue #1505

Over the past year, Aird2.0 has further improved file compression rate(20% higher) and read speed than Aird1.0.
GPL-based packages were also removed.

2024-04-26 14:19 UTC, SteffenHeu commented
Hi lumiaoshan, thanks for the fast update. Can you add a test for the import of the aird files? We have the DataImportTestGenerator class to help you do that. You can convert one of the mzml files and maybe the tdf files (all of them are super small) to aird format and use them. This will ensure that nothing gets broken in future updates.

2024-06-25 14:41 UTC, SteffenHeu commented
> Hi lumiaoshan, thanks for the fast update. Can you add a test for the import of the aird files? We have the DataImportTestGenerator class to help you do that. You can convert one of the mzml files and maybe the tdf files (all of them are super small) to aird format and use them. This will ensure that nothing gets broken in future updates.

@lumiaoshan

2024-07-18 15:51 UTC, lumiaoshan commented
Hi, @SteffenHeu , I am very excited to see the extremely fast development progress for MZmine these days, with a large number of code submissions every week. I have completed the Aird integration code and test code. Please check to see if it can be merged into the trunk.

2024-07-19 08:31 UTC, SteffenHeu requested changes
Thank you! 
Looks great so far, i got some small questions/comments

2024-07-19 08:31 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/io/import_rawdata_aird/AirdImportTask.java
> +        newMZmineFile = new IMSRawDataFileImpl(this.file.getName(), file.getAbsolutePath(),
I can see no differentiation in the loader classes for IMS files and non ims files. All scans belonging to one frame need to be grouped into frames with their mobility scans to be properly processed. Is this currently dealt with? otherwise it may be better to disable the import for IMS-aird

2024-07-19 08:31 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/io/import_rawdata_aird/AirdImportTask.java
> +    System.out.println(file.getName() + ":" + (System.currentTimeMillis() - start));
remove system.out please

2024-07-19 08:31 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/io/import_rawdata_aird/loader/BaseLoader.java
> +      e.printStackTrace();
wrap with logger.log(WARNING, e.getMessage, e);

2024-08-06 05:36 UTC, lumiaoshan commented on mzmine-community/src/main/java/io/github/mzmine/modules/io/import_rawdata_aird/loader/BaseLoader.java
> +      e.printStackTrace();
Thank you for pointing out the problem, I have finished the modification of the relevant code.

2024-11-13 10:06 UTC, SteffenHeu commented on mzmine-community/build.gradle
> +    maven { name "Alibaba" ; url "https://maven.aliyun.com/repository/public" }
can you upload to maven central so these are not needed? 
If local libraries are necessary, we have the local-repo folder

2024-11-13 10:06 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/io/import_rawdata_all/AllSpectralDataImportMainTask.java
> +    try {
cannot merge like this, all that should not be required if you make a user account

2025-07-31 14:28 UTC, SteffenHeu commented
Closing this PR for now, please open a new one in case it becomes active again ;)

2025-07-31 14:28 UTC, closed without merging