Add RepeatingUnitSuggester
mzmine/mzmine pull request #1831
Opened 2024-05-08 11:14 UTC by kyrasolaris01

2024-05-09 16:08 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotParameters.java
> +        featureList.getValue().getMatchingFeatureLists()[0]);
index out of range if no feature lists are selected like in batch mode

2024-05-09 16:10 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotParameters.java
> +    dialog.getParamsPane().add(new Label("Suggested repeating units:"), 2, 0);
Why not just put this label into the VBox?

2024-05-09 16:15 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +        .flatMapToDouble(row -> DoubleStream.of(row.getAverageMZ())).toArray();
ChatGPT? :D
just mapToDouble you have a single value that you want to map to

2024-05-09 16:15 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +        .flatMapToInt(row -> IntStream.of(row.getRowCharge())).toArray();
same here mapToInt

2024-05-09 16:16 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +    for (int i = 0; i < masses.length; i++) {
could be <masses.length-1

2024-05-09 16:18 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +            Math.round((masses[j] - masses[i]) * 1000) / 1000.0); // Round to 3 decimal places
I guess Math.round(Math.abs()) might be better. Rounding sometimes depend on negative/positive number

2024-05-14 06:15 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +    double[] products = new double[mzValues.length];
rename to neutralMasses, more meaningful

2024-05-14 06:20 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +      for (int j = i + 1; j < masses.length; j++) {
maybe we should put a limit here for the maximum number of features to check. and then use it in both loops. Feature detection could end up in 1M features and that would be hard in a 2D loop 

```java
int maxFeaturesToCheck = Math.min(10000, masses. length);
```

2024-05-14 06:25 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +    for (int i = 0; i < masses.length - 1; i++) {
another thing you can do to limit the number of comparisons - sort the masses array and then stop the inner loop if the delta mass grows too big to detect repeating units like above 300 or so.

2024-05-14 06:40 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +  private Map<Double, Integer> calculateDeltaFrequencies(double[] masses) {
you could add a second argument double massTolerance and maybe add a text input or combobox with limited options above the repeating unit component.  

You can use values like 0.5, 0.1, 0.01, 0.001, 0.0005 and then just reverse the math:
```java
double delta = 
            Math.round(Math.abs(masses[j] - masses[i]) / massTolerance) * massTolerance;
```

2024-05-14 06:40 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +  private Map<Double, Integer> calculateDeltaFrequencies(double[] masses) {
this would allow for different resolutions

2024-05-14 06:43 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +      mfRange.addIsotope(f, 0, 100);
maybe reduce the number of all the atoms - its  only for repeating units right?
So those should be relatively small units?

2024-05-14 06:48 UTC, ansgarkorf commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +  private Map<Double, Integer> calculateDeltaFrequencies(double[] masses) {
good idea. One could also use the mzTolerance extracted from the chromatogram building -> extractMzToleranceFromPreviousMethods()

2024-05-14 06:51 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +        double formulaMass = MolecularFormulaManipulator.getMass(formula);
It would be amazing if we finally create a method out of this. This code is already copied a couple of times in different places. 
Maybe MolecularFormulaPredictor or something similar. 
We could set all the values needed and we could activate/deactivate all checks and then predict formulas here in a single line of code.

2024-05-14 06:55 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +  private Map<Double, Integer> calculateDeltaFrequencies(double[] masses) {
Could work. You need to be aware that the absolute tolerance might be 0 and only ppm. 
But then just give in a number like
```java
double tolerance = tol.getMzToleranceForMass(200);
```

2024-05-14 06:58 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +  private Map<Double, Integer> calculateDeltaFrequencies(double[] masses) {
One thing to consider is that the mz in the map is then quite low resolution....
Maybe instead of counting you could add all the values to a DoubleList as value:
Map<Double, DoubleList> from fastutil. 
This way you can recalculate the actual median or mean of the mzs and not the rounded values

2024-05-14 07:00 UTC, kyrasolaris01 commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +  private Map<Double, Integer> calculateDeltaFrequencies(double[] masses) {
I like that idea! Using the median should result in much better formula prediction results.

2024-05-14 18:16 UTC, kyrasolaris01 commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +        double formulaMass = MolecularFormulaManipulator.getMass(formula);
yep, but another time

2024-05-14 18:31 UTC, kyrasolaris01 commented
done

2024-05-15 12:19 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotSetupDialog.java
> +    ObservableList<String> newItems = newListView.getItems();
You can just check for equality:
Objects.equals is null safe
otherwise a.equals(b)

```java 
  @Test
  public void testLists() {
    var a = List.of("Hallo", "test", "5");
    var b = new ArrayList<>(a);
    var c = a.stream().toList();

    assertTrue(Objects.equals(a, b));
    assertTrue(Objects.equals(a, c));
    assertTrue(Objects.equals(b, c));
    assertTrue(ListUtils.isEqualList(a, b));
    assertTrue(ListUtils.isEqualList(a, c));
    assertTrue(ListUtils.isEqualList(b, c));
  }
```

2024-05-15 12:19 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/KendrickMassPlotSetupDialog.java
> +    ObservableList<String> newItems = newListView.getItems();
so the whole method can be removed

2024-05-15 12:22 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +      protected ObservableList<String> call() {
You should use List<String> here instead of ObservableList

2024-05-17 15:57 UTC, kyrasolaris01 commented
done,
@robinschmid I reverted to my old findTopNDeltaMedians method. Yours gave weird result. I guess the sorting was wrong.

2024-05-17 17:07 UTC, robinschmid commented
Ok only issue was that the comparator needs to be reversed 
```java
  private List<Double> findTopNDeltaMedians(Map<Double, DoubleList> deltaMap, int topN) {
    // Get the top N entries based on the size of the DoubleList
    return deltaMap.values().stream()
        .sorted(Comparator.comparing(List::size, Comparator.reverseOrder()))
    // only topN deltas with most occurrence
    .limit(topN)
// calculate median of mz
        .map(DoubleCollection::toDoubleArray).map(MathUtils::calcMedian).toList();
```

2024-05-17 17:11 UTC, robinschmid requested changes
I forgot to send the review and it was pending sorry

2024-05-17 17:11 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/kendrickmassplot/RepeatingUnitSuggester.java
> +        if (!predictedFormula.isBlank() && !list.contains(predictedFormula)) {
still the same issue. list.contains(predictedFormula) will always be false because you are adding a composite string here.

Best would be to use a List<FormulaWithExactMz>

2024-05-23 18:17 UTC, merged