Empty scan warning fix
mzmine/mzmine pull request #1843
Opened 2024-05-13 15:57 UTC by SteffenHeu

only show if ms1 scan is empty

2024-05-13 16:52 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/project/impl/RawDataFileImpl.java
> +    if (!containsEmptyScans && newScan.isEmptyScan() && newScan.getMSLevel() == 1) {
Also the downstream messages could say MS1 scan was empty?

2024-05-13 16:54 UTC, robinschmid submitted a review, later dismissed
Looks good to me. Maybe we can add that MS1 scans were empty? I like the added filter though

2024-05-13 16:54 UTC, robinschmid commented
can be merged though

2024-05-13 20:34 UTC, SteffenHeu commented
Also added col visibility fixes @robinschmid

2024-05-14 06:21 UTC, ansgarkorf commented on mzmine-community/src/main/java/io/github/mzmine/gui/mainwindow/MainWindowController.java
>            tip.setText("""
rename peaks to signals

2024-05-15 16:06 UTC, robinschmid requested changes
Looks good to me. Only small things

2024-05-15 16:06 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableColumnMenuHelper.java
> +  private record ColIdWrapper(ColumnID id) {
maybe add javadoc for the future steffen to understand.
So you added this to just have a simpler equals method?

2024-05-15 16:06 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableFX.java
> +    setVisible(ColumnType.ROW_TYPE, parentType, SimilarityType.class, toggledState);
Good here its already SimilarityType so it matches with the spectral library match typ

2024-05-15 16:06 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/parameters/parametertypes/datatype/DataTypeCheckListParameter.java
> +  private void defaultDisableColumns() {
this also overwrites the last setting of the user right? is it possible to check if there was something set before?

2024-05-16 10:38 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableColumnMenuHelper.java
> +  private record ColIdWrapper(ColumnID id) {
added to make use of the Stream.distinct method since you cannot put a comparator there

2024-05-16 11:02 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/parameters/parametertypes/datatype/DataTypeCheckListParameter.java
> +  private void defaultDisableColumns() {
it should not, since it is added in the contstructor before the settings are loaded from the xml.

2024-05-17 08:46 UTC, merged