Add shortcut keys, refactor row deletion into module
mzmine/mzmine pull request #1937
Opened 2024-06-28 12:20 UTC by SteffenHeu

- added shortcuts
  - tab selection (ctrl + pgUP/DOWN)
  - row deletion (del)
  - close parameter window (esc)
  - run module (ctrl + enter)

2024-07-16 14:00 UTC, robinschmid requested changes
I like the idea of saving manual steps. 
Maybe we can add some checks to make it not fail silently. 
Also this might be interesting as a full module actually for people to feed in lists of features to remove from a downstream tool.

2024-07-16 15:29 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsParameters.java
> +      "Row ID from the specific feature list, separated by ; with no spaces.");
why not encourage proper formatting anyway?

2024-07-16 15:33 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsTask.java
> +  protected void process() {
how would 1 work? we have no way of differentiating where the value comes from (prior module call or from a batch config?

2024-07-16 15:33 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableContextMenu.java
> +        DeleteRowsModule.deleteWithConfirmation(table.getFeatureList(), selectedRows);
I think from the right click menu and jsut one row its fine.

2024-07-16 15:35 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableFX.java
> +    setFeatureList(flist);
It implements a method from the ListChangeListener. Bad idea to delete.

2024-07-16 15:36 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableFX.java
> +    setFeatureList(flist);
Added `@Override` for clarity

2024-07-16 15:53 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsModule.java
> +public class DeleteRowsModule extends AbstractProcessingModule {
was not added until now on purpose. can do it maybe

2024-07-16 15:55 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsTask.java
> +    final List<FeatureListRow> rows = FeatureUtils.idStringToRows(flist, rowIdStr);
added an exception to the method

2024-07-17 08:32 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/parameters/dialogs/EmptyParameterSetupDialogBase.java
> +      if (event.getCode() == KeyCode.ENTER && event.isControlDown()) {
closing a combobox works

2024-07-17 09:36 UTC, robinschmid approved these changes
Looks good just small things / questions. Not quite sure if closing dialogs with just escape might have drawbacks.

2024-07-17 09:36 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsParameters.java
> +      "Row ID from the specific feature list, separated by , with no spaces.");
with no spaces can be removed and then just do a split.strip on each element

2024-07-17 09:36 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsTask.java
> +                : "NOT LOGGED IN"), getModuleClass(), getParameters(), moduleCallDate);
no need to change but there is also a method to get the user name as an optional CurrentUserService.getUserName

2024-07-17 09:36 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/featurelisttable_modular/FeatureTableFX.java
> +    setFeatureList(flist);
Oh I did not realize this was from the itnerface. 
Maybe this could still be the better approach to updating the table? 
Or what is the reason to clear and recreate the whole table instead of just the rows?

this could be extracted from onChange:
```java
      getRoot().getChildren().clear();
      rowItems.clear();
      // add rows
      for (FeatureListRow row : featureListProperty.get().getRows()) {
        final ModularFeatureListRow mrow = (ModularFeatureListRow) row;
        rowItems.add(new TreeItem<>(mrow));
      }
      getRoot().getChildren().addAll(filteredRowItems);
      this.sort();
```

2024-07-17 09:36 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/parameters/dialogs/EmptyParameterSetupDialogBase.java
> +      if (event.getCode() == KeyCode.ESCAPE) {
maybe add the isShortcutDown?
Not sure if this will create issues otherwise. 
Is there any other software that kills dialogs on just escape?

2024-07-17 11:13 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/parameters/dialogs/EmptyParameterSetupDialogBase.java
> +      if (event.getCode() == KeyCode.ESCAPE) {
eg outlook when writing an email

2024-07-17 11:15 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsParameters.java
> +      "Row ID from the specific feature list, separated by , with no spaces.");
why not simply encourage proper formatting, the strip was already added.

2024-07-17 12:15 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_deleterows/DeleteRowsParameters.java
> +      "Row ID from the specific feature list, separated by , with no spaces.");
why is it less proper? 
The statement suggests that spaces will break the parsing but thats not the case.

2024-07-17 12:15 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/parameters/dialogs/EmptyParameterSetupDialogBase.java
> +      if (event.getCode() == KeyCode.ESCAPE) {
ok we can try it

2024-07-17 13:06 UTC, merged