Other dectectors - add manual integration pane
mzmine/mzmine pull request #2000
Opened 2024-07-29 14:04 UTC by SteffenHeu

2024-08-02 16:41 UTC, robinschmid requested changes
Looks good so far. 
Maybe we can define how the other feature "raw" chromatograms and processed chromatograms could be structured. Like what is the most common use case. 

I think its best to handle both as OtherFeature and just have a list of the raw and a list of the processed ones.

2024-08-02 16:41 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/chromatogramplot/ChromatogramPlotModel.java
> +      FXCollections.observableHashMap());
Just thought about how we can build something in the future to make this easier. 
In another PR we should create a EChartViewerModel class or just extend the EChartViewer so that it holds all the different properties that we need to control and define a chart. 
This way it would be easy to have any number of charts in an MVC and easily control the look and feel.

2024-08-02 16:41 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/integrationplot/Boundary.java
> +enum State {
Something wrong? Boundary.java but contains class State?

2024-08-02 16:41 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/integrationplot/IntegrationPane.java
> +    rawFile.addListener((_, _, file) -> {
most of the time it feels to me that addListener should be subscribe(newValue -> to already trigger an update at with the initial value. Of course dependent on the actual logic inside. Just maybe check if all those listeners should be triggered already or not.

2024-08-02 16:41 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/integrationplot/IntegrationPlotViewBuilder.java
> +  private final Runnable onEditPressed;
I still struggle how the runnable actions like a button click can be done best... sometimes feel like adding to the model a Property<Runnable> is the easiest compared to passing it in here.  

In this case you got many actions that are linked so I think just having one Consumer<IntegrationEvent> and just pass in the events like finish, abort, edit, ... would be a good solution that only needs one method with a switch on an enum

2024-08-02 16:41 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/multidetector/DetectorPane.java
> +    vbox.maxWidth(250);
does this need to be so strict and hard coded? THis does not work with auto layout?

2024-08-02 16:41 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/multidetector/DetectorPane.java
> +    minHeight(200);
same here

2024-08-04 15:48 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/datamodel/otherdetectors/OtherTimeSeriesDataImpl.java
> +  private final ObservableMap<OtherTimeSeries, ObservableList<OtherFeature>> processedFeatures = FXCollections.observableHashMap();
no, this structure is fine. I first tried to just make a list, but you often want all features in one trace. I think flat mapping is easier than having to filter on must of the calls.

2024-08-04 15:52 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/multidetector/DetectorPane.java
> +    vbox.maxWidth(250);
yes, because it will change sizes otherwise when you select a different value in the combo boxes.

2024-08-05 07:37 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/visualization/otherdetectors/integrationplot/IntegrationPane.java
> +    rawFile.addListener((_, _, file) -> {
No, the listeners are are fine. The constructors trigger the listeners right away. the thing is that the combo box always triggered NPEs when the listeners were triggered too early.

2024-08-05 13:53 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/datamodel/featuredata/IntensityTimeSeries.java
> +  IntensityTimeSeries subSeries(MemoryMapStorage storage, float start, float end);
done here for othertimeseries. for iontimeseries this will be handled in a separate PR

2024-08-05 13:54 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/datamodel/features/types/otherdectectors/OriginalTimeSeriesType.java
> +public class OriginalTimeSeriesType extends DataType<OtherTimeSeries> implements NoTextColumn,
to be added to the OtherFeature

2024-08-05 13:55 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/datamodel/features/types/otherdectectors/OtherFeatureDataType.java
> +public class OtherFeatureDataType extends DataType<OtherTimeSeries> implements NoTextColumn,
for now it's jsut intended for the otherfeature to hold the resolved data, that's why it's in the otherdetectors package.

2024-08-06 16:20 UTC, robinschmid approved these changes
Pretty much done. Great restructure of into features

2024-08-06 16:20 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/datamodel/otherdetectors/OtherTimeSeriesDataImpl.java
> +  private final List<OtherFeature> processedFeatures = new ArrayList<>();
maybe a good idea to synchronize all add / clear / remove operations on processedFeatures with a CloseableReentrantReadWriteLock. What do you think? 
I think we should do this also for ModularFeatureList actually for the rows.

2024-08-06 16:20 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/datamodel/otherdetectors/OtherTimeSeriesDataImpl.java
> +    processedFeatures.removeAll(currentFeatures);
maybe just do removeif instead of a two step approach:
```java
    processedFeatures.removeIf(f -> Objects.equals(f.get(RawTraceType.class), rawTrace));
```
All this could be wrapped into a write lock

2024-08-06 16:20 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/gui/chartbasics/simplechart/providers/impl/features/OtherFeatureProvider.java
> +public class OtherFeatureProvider implements PlotXYDataProvider {
rename to OtherFeatureDataProvider? Otherwise it sounds like it provides the feature itself. maybe easier to find as well

2024-08-07 15:34 UTC, robinschmid commented
Looks fantastic now

2024-08-07 15:34 UTC, merged