Baseline correction
mzmine/mzmine pull request #2010
Opened 2024-08-02 12:53 UTC by SteffenHeu

Add multiple methods for baseline correction. Not all are currently used for MS data, but may be useful for UV data or so. So We'll keep them for now.

uses #2003

2024-08-05 13:58 UTC, robinschmid requested changes
Looks good so far

2024-08-06 14:33 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_baselinecorrection/AbstractBaselineCorrector.java
> +  protected double[] yBufferRemovedPeaks = new double[0];
because then i can just check for legnth and dont have to do an extra null check

2024-08-06 14:34 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_baselinecorrection/AbstractBaselineCorrector.java
> +  public AbstractBaselineCorrector(MemoryMapStorage storage, int numSamples, String suffix,
It's just null for the default constructor, which instance is never used

2024-08-06 14:37 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_baselinecorrection/AbstractBaselineCorrector.java
> +   * even if they are contained in one of the ranges.
Because you cannot extrapolate with most polynomial functions from math3

2024-08-06 15:21 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/featdet_baselinecorrection/AbstractBaselineCorrector.java
> +  protected <T extends IntensityTimeSeries> T createNewTimeSeries(T timeSeries, int numValues,
Every time i programmed something like this there have always been caveats to the implementation i used somewhere previosly. I think it's totally fine to not put 8 lines of code into an utility class.

2024-08-26 11:14 UTC, merged