Fragmentation
mzmine/mzmine pull request #2020
Opened 2024-08-07 07:26 UTC by SteffenHeu

fragment graph for ms2 spectra

2024-08-27 14:12 UTC, robinschmid requested changes
Code looks great and the dashboard is amazing. 
I mostly found issues with the TableColumns. JavaFx tables and columns are quite complex so it might be better to use the factories of TableColumns and create new ones so that it becomes easier in the future.  
Currently the ColumnValue types are sometimes String sometimes Double or just the TableView Row type again. 

I pushed minor changes that came up in the review. Mostly finals and npe checks.

Also created an issue to track other future ideas that will not go into this PR. 
https://github.com/mzmine/mzmine/issues/2055

2024-08-28 12:08 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/tools/fraggraphdashboard/spectrumplottable/NeutralLossAnnotation.java
> +public class NeutralLossAnnotation extends AbstractXYAnnotation {
yes but will be uses

2024-08-28 13:54 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/tools/fraggraphdashboard/nodetable/EdgeTable.java
> +        "Mass diff.\n(meas.)");
measured

2024-08-30 12:12 UTC, robinschmid approved these changes
Great change with the TableColumns factories. It is much more readable now and easy to understand the structure of the tables. 

Can be merged. See my PR to your branch that harmonized the factories in TableColumns and added the Comparator as option so that mass difference columns can be created with one line.

As Property will create a TableColumn<T, Double> whereas DoubleProperty creates a TableColumn<T, Number> but thats ok.

2024-09-02 08:08 UTC, merged