DIA PASEF support
mzmine/mzmine pull request #2102
Opened 2024-09-27 15:12 UTC by SteffenHeu

2024-11-14 21:23 UTC, robinschmid requested changes
Thanks for improving this module. The structure is much better now. Still quite complex and took some time to fully understand all things going on. 

Mostly comments for small changes like null checks etc.

2024-11-14 21:23 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +        result.add(eic);
could this mean that the same EIC is added multiple times? 
Maybe use a HashSet instead while collecting and then later you could turn it into a list. 
Or stream.distinct on your list to keep the mz sorting of the scan. HashSet would ruin the sorting.

2024-11-14 21:23 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +      final IonTimeSeries<?> eic = eics.get(mz);
Just thought about this again. Quite complex overall but the code is greatly improved. 

Here this means:
1. the ranges were added largest feature first - so the largest feature has the priority
2. key ranges in this map are just the data point mz range so they may be quite small - could this make problems matching the signals here or it should not because the datapoints of the feature should actually be from exactly this ms2?
3. Or do we need to make the range a little wider?

2024-11-14 21:23 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +      // todo: to make this efficient, merge PR #2016
done, remove

2024-11-14 21:32 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> -    if (adapTask != null) {
can delete the @Override cancel method in this task

2024-11-15 09:24 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +    if (ms2Flists.isEmpty()) {
these are just the flists generated for the ms2 spectra. can be removed

2024-11-15 09:49 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +      final IonTimeSeries<?> eic = eics.get(mz);
1. that's the case for the chromatogram building under any circumstance, so i thought i'd keep it like that here. 
2. adapted to either use the data point mz range or mzTolerance around feature mz using RangeUtils.max

2024-11-15 09:51 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +        result.add(eic);
stream distinct it is

2024-11-15 11:52 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/datamodel/featuredata/IonTimeSeries.java
> +        default -> (IonTimeSeries<T>) IonTimeSeries.EMPTY;
done

2024-11-15 12:47 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/IsolationWindow.java
> +    return mobilityIsolation == null || mobilityIsolation.contains((float) scan.getMobility());
Oh that's odd. I think it should test both at this point. I will change that

2024-11-17 21:52 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +      final IonTimeSeries<?> eic = eics.get(mz);
Actually i thought about thgis again. Since all the datapoints are contained in the ms2 eics (the feature lists for each isolation window), the data point range is fine since every non noise dp should be in an eic.

2024-11-18 15:13 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/IsolationWindow.java
> +//    }
should this be added? Comment on GH says yes but not sure why it is commented out.

2024-11-18 15:40 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/IsolationWindow.java
> +    return mobilityIsolation == null || mobilityIsolation.contains((float) scan.getMobility());
there is still commented out checks for mz - maybe they were supposed to be added?

2024-11-18 15:50 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +      final IonTimeSeries<?> eic = eics.get(mz);
ok makes sense. Just wanted to check if there is a pitfall

2024-11-18 16:54 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +      if (overlap > 0.95) {
the overlap was 0.997-0.999 most of the time

2024-11-18 17:45 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/DiaMs2CorrTask.java
> +          .sorted(Comparator.comparingDouble(mw -> mw.window().overlap(window))).toList();
done

2024-11-18 17:46 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/filter_diams2/IsolationWindow.java
> +//    }
no, unnecessary

2024-11-20 11:00 UTC, robinschmid approved these changes

2024-11-20 21:50 UTC, merged