Simplify Image correlation Task
mzmine/mzmine pull request #2127
Opened 2024-10-11 18:29 UTC by robinschmid

Relies on PR #2126 for minor changes to FeatureDataAccess

The data preparation was more complex than need be.

2024-10-26 06:54 UTC, robinschmid commented
Updated and ready

2024-10-28 15:19 UTC, SteffenHeu commented
I'm getting stack overflow erros

```
2024-10-28 14:33:03 SEVERE io.github.mzmine.taskcontrol.impl.WrappedTask run Unhandled exception java.lang.StackOverflowError while processing task Identification of co-located images Aligned feature list peak
java.lang.StackOverflowError
	at io.github.mzmine.util.collections.StreamUtils.processPairs(StreamUtils.java:127)
	at io.github.mzmine.util.collections.StreamUtils.processPairs(StreamUtils.java:127)
```

2024-10-28 15:20 UTC, SteffenHeu requested changes

2024-10-28 15:20 UTC, SteffenHeu commented on utils/src/main/java/io/github/mzmine/util/collections/StreamUtils.java
> +    return processPairs(items, isCanceled, parallel, processor);
Calling itself

2024-10-30 12:17 UTC, SteffenHeu approved these changes

2024-10-30 12:19 UTC, merged