GC-EI-MS spectral networking
mzmine/mzmine pull request #2236
Opened 2024-11-18 20:41 UTC by robinschmid

2024-11-18 20:54 UTC, ansgarkorf commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/cosine_no_precursor/NoPrecursorCosineSpectralNetworkingParameters.java
> +    param.setParameter(ModifiedCosineSpectralNetworkingParameters.MIN_COSINE_SIMILARITY, minCosine);
Does it make sense to re-use the ModifiedCosine...Parameters here? The current min is set to 4, which is to low for GC. Lets go with at least 8.

2024-11-18 20:56 UTC, ansgarkorf commented on mzmine-community/src/main/java/io/github/mzmine/modules/tools/batchwizard/builders/BaseWizardBatchBuilder.java
> +        NoPrecursorCosineSpectralNetworkingParameters.setAll(param, 4, 0.7, mzTolScans,
Set min number of matched signals to 8

2024-11-18 20:58 UTC, ansgarkorf requested changes
Looks good and works as we thought. Please look at the 2 comments regarding default values.

2024-11-19 07:45 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/cosine_no_precursor/NoPrecursorCosineSpectralNetworkingParameters.java
> +    param.setParameter(ModifiedCosineSpectralNetworkingParameters.MIN_COSINE_SIMILARITY, minCosine);
True for GC it should be higher. Not too much though I would say. 
Because a structural modification may decrease the number of matching signals. 
Then the best decider is the cosine similarity

2024-11-19 09:10 UTC, SteffenHeu requested changes

2024-11-19 09:10 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/cosine_no_precursor/NoPrecursorCosineSpectralNetworkingParameters.java
> +      Signal filters to limit the number of signals etc.
etc?

2024-11-19 09:10 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/cosine_no_precursor/NoPrecursorSignalFiltersParameters.java
> +  }
create new parameters, otherwise they always have the same value

2024-11-19 09:10 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/cosine_no_precursor/NoPrecursorCosineSpectralNetworkingParameters.java
> +        ModifiedCosineSpectralNetworkingParameters.MIN_COSINE_SIMILARITY, signalFilters);
create new parameters

2024-11-19 09:10 UTC, SteffenHeu commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/cosine_no_precursor/NoPrecursorSignalFiltersParameters.java
> +  }
use can use the same name SignalFiltersParameters.intensityPercentFilter.getName()

2024-11-19 09:30 UTC, robinschmid commented on mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/group_spectral_networking/cosine_no_precursor/NoPrecursorCosineSpectralNetworkingParameters.java
> +      Signal filters to limit the number of signals etc.
Made some static name and description in SignalFiltersParamters
```
Signal filters to limit the number of signals based on a maximum number
and a target percentile of intensity retained. Above a signal threshold,
signals are limited so that XX % of intensity remains. Then the signals are limited to the max N signals.
```

2024-11-19 10:04 UTC, merged